spring:
    datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://120.27.248.244:3306/study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: HuangBo@2019