server:
    port: 8080
    servlet:
        context-path: /SpringbootCRUD
spring:
    datasource:
        driver-class-name:  com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://49.4.52.68:3306/study?useUnicode=true&characterEncoding=utf8&characterSetResults=utf8
        username: root
        password: HuangBo@2019
mybatis:
    mapper-locations: classpath*:mapping/**/*.xml